### ISSUE TITLE
Export Merged Acc. schedule to XML - wrong format BC 19/BC18

### ISSUE THREAD

**Issue by martinbokuvka** [AutoContCZ/AC-Solutions#1]
Hello,

we found bug in SK localization, Export Merged Acc. schedule to XML.
Exported file does not have correct format in lines part.
After import to UZPODv14, only header is imported and lines are blank.
In BC 16 this function is working correctly and lines are imported.
Please see attached files. [UZPOD14_BC.zip](https://github.com/AutoContCZ/AC-Solutions/files/8323424/UZPOD14_BC.zip)
XML mapping in BC 19 is imported
![BC19mapping](https://user-images.githubusercontent.com/102150033/159462824-adf38a02-33a8-4dc4-a031-459ab096362f.PNG)
.

**Comment by ACPJanousek** [comment]
solved
